name: macchina-remote-sdk-ci
on: [push]
jobs:
  linux-gcc-cmake:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install cmake ninja-build libssl-dev
      - run: cmake -H. -Bcmake-build -GNinja -DENABLE_WEBTUNNELCLIENTLIB=ON && cmake --build cmake-build --target all

  macos-clang-cmake:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: brew install openssl@3 ninja
      - run: cmake -H. -Bcmake-build -GNinja -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DENABLE_WEBTUNNELCLIENTLIB=ON && cmake --build cmake-build --target all

  windows-msvc-cmake:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - run: cmake -S. -Bcmake-build -DENABLE_WEBTUNNELCLIENTLIB=ON
      - run: cmake --build cmake-build --config Release
