name: Publish Release
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release Channel'
        required: true
        default: 'releases'
        type: choice
        options:
          - releases
          - releases-staging

jobs:
  release_win64:
    runs-on: windows-2022
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 -S. -Bcmake-build
          cmake --build cmake-build --config Release
      -
        name: Sign
        run: |
          echo '${{ secrets.SIGNING_CERT }}' >CodeSigningCert.b64
          certutil -decode CodeSigningCert.b64 CodeSigningCert.pfx
          & 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x86\\signtool.exe' sign /f CodeSigningCert.pfx /p '${{ secrets.SIGNING_PASS }}' /tr http://timestamp.digicert.com /td sha256 /fd sha256 /v cmake-build\\bin\\Release\\*.exe
      -
        name: Zip
        run: 7z a -tzip remote-clients.zip cmake-build\bin\Release\*.exe
      -
        name: Install SSH Key
        run: |
          mkdir ~/.ssh
          echo '${{ secrets.MACCHINA_IO_SSH_HOST_KEY }}' >~/.ssh/known_hosts
          echo '${{ secrets.MACCHINA_SSH_KEY }}' >~/.ssh/id_rsa
      -
        name: Copy to Web Server
        run: |
          ssh ${{ secrets.MACCHINA_USER }}@web.macchina.io mkdir -p releases/sdk/windows/10/AMD64/
          scp cmake-build\bin\Release\*.exe remote-clients.zip ${{ secrets.MACCHINA_USER }}@web.macchina.io:releases/sdk/windows/10/AMD64/

  release_ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Packages
        run: sudo apt update && sudo apt install cmake ninja-build libssl-dev
      - 
        name: Build
        run: cmake -H. -Bcmake-build -GNinja && cmake --build cmake-build --target all
      -
        name: Strip
        run: strip cmake-build/bin/*
      -
        name: GZip
        run: |
          (cd cmake-build/bin && tar cfz ../../remote-clients.tar.gz remote-*)
          gzip cmake-build/bin/*
      -
        name: Install SSH Key
        run: |
          mkdir ~/.ssh
          echo '${{ secrets.MACCHINA_IO_SSH_HOST_KEY }}' >~/.ssh/known_hosts
          echo '${{ secrets.MACCHINA_SSH_KEY }}' >~/.ssh/id_rsa
          chmod go-rwx ~/.ssh/id_rsa
      -
        name: Copy to Web Server
        run: |
          ssh ${{ secrets.MACCHINA_USER }}@web.macchina.io mkdir -p releases/sdk/ubuntu/20.04/x86_64
          scp cmake-build\bin\*.gz remote-clients.tar.gz ${{ secrets.MACCHINA_USER }}@web.macchina.io:releases/sdk/ubuntu/20.04/x86_64

  release_ubuntu2204:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Packages
        run: sudo apt update && sudo apt install cmake ninja-build libssl-dev
      - 
        name: Build
        run: cmake -H. -Bcmake-build -GNinja && cmake --build cmake-build --target all
      -
        name: Strip
        run: strip cmake-build/bin/*
      -
        name: GZip
        run: |
          (cd cmake-build/bin && tar cfz ../../remote-clients.tar.gz remote-*)
          gzip cmake-build/bin/*
      -
        name: Install SSH Key
        run: |
          mkdir ~/.ssh
          echo '${{ secrets.MACCHINA_IO_SSH_HOST_KEY }}' >~/.ssh/known_hosts
          echo '${{ secrets.MACCHINA_SSH_KEY }}' >~/.ssh/id_rsa
          chmod go-rwx ~/.ssh/id_rsa
      -
        name: Copy to Web Server
        run: |
          ssh ${{ secrets.MACCHINA_USER }}@web.macchina.io mkdir -p releases/sdk/ubuntu/22.04/x86_64
          scp cmake-build\bin\*.gz remote-clients.tar.gz ${{ secrets.MACCHINA_USER }}@web.macchina.io:releases/sdk/ubuntu/22.04/x86_64
        
  release_macos12:
    runs-on: macos-12
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Packages
        run: brew install openssl@3 ninja
      - 
        name: Build
        run: cmake -H. -Bcmake-build -GNinja -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DOPENSSL_USE_STATIC_LIBS=TRUE && cmake --build cmake-build --target all
      -
        name: Strip
        run: strip cmake-build/bin/*
      -
        name: GZip
        run: |
          (cd cmake-build/bin && tar cfz ../../remote-clients.tar.gz remote-*)
          gzip cmake-build/bin/*
      -
        name: Install SSH Key
        run: |
          mkdir ~/.ssh
          echo '${{ secrets.MACCHINA_IO_SSH_HOST_KEY }}' >~/.ssh/known_hosts
          echo '${{ secrets.MACCHINA_SSH_KEY }}' >~/.ssh/id_rsa
          chmod go-rwx ~/.ssh/id_rsa
      -
        name: Copy to Web Server
        run: |
          ssh ${{ secrets.MACCHINA_USER }}@web.macchina.io mkdir -p releases/sdk/ubuntu/22.04/x86_64
          scp cmake-build\bin\*.gz remote-clients.tar.gz ${{ secrets.MACCHINA_USER }}@web.macchina.io:releases/sdk/ubuntu/22.04/x86_64
